services:
  dev:
    container_name: "dev"
    # For development
    stdin_open: true
    tty: true
    command: tail -F /dev/null
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: "playground"
        UBUNTU_VERSION: "22.04"
        PYTHON_VERSION: "3.10"
        POETRY_VERSION: "1.8.1"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DISABLE_REQUIRE=1
    volumes:
      - .:/code
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]